# base URL for the API
@base=http://localhost:5000/api
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc4NTIzOTA2NCwianRpIjoiOGYxNzU3ODYtMThjNy00Njg0LTg3OWUtYzE5MzQzN2JkMTZjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjI2ZjdmYzBmLTY4YTAtNDNhYy05MGYyLWVjODI0ZWFjNWZhZSIsIm5iZiI6MTc4NTIzOTA2NCwiY3NyZiI6Ijk4NTk1NTA0LTE5NmUtNGFkZC04ZTgxLTlkMmFkNTYwMmNjZSIsImV4cCI6MTc4NTI0MjY2NCwicm9sZV9uYW1lIjoiZW1wbG95ZWUifQ.cMLTPBlEwcO2QYZRXCmlS7BpDoom2nS7sq8VGP4gdm4


### Auth
POST {{base}}/auth/login
Content-Type: application/json

{
  "email": "john.doe@hrsystem.com",
  "password": "EmployeePass123!"
}

### POST Leave
POST {{base}}/leave
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "reason": "Family vacation",
    "leave_type_id": "4641ac8a-961a-447f-9957-294acf906dcd",
    "start_date": "2026-07-01",
    "end_date": "2026-07-28"
}
