"""add staff_no attribute to employee table

Revision ID: 75dabb2b79ec
Revises: e653309333d2
Create Date: 2026-07-27 16:00:16.629248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75dabb2b79ec'
down_revision = 'e653309333d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_no', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint("uq_employees_staff_no", ['staff_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint("uq_employees_staff_no", type_='unique')
        batch_op.drop_column('staff_no')

    # ### end Alembic commands ###
